In [1]:
! pip install sympy

In [2]:
import numpy as np
import sympy

In [3]:
A = np.matrix([[1, 2, 1, 1], [2, 2, 2, 2], [1, 2, 1, 1]])

In [4]:
sympy.Matrix(A).rref()

(Matrix([
 [1, 0, 1, 1],
 [0, 1, 0, 0],
 [0, 0, 0, 0]]),
 (0, 1))

In [5]:
A = np.matrix([[1, 2, 2], [1, 3, 3]])

In [6]:
sympy.Matrix(A).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 1]]),
 (0, 1))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generate random matrices
A = np.random.rand(20, 40)
B = np.random.randn(20, 40)
# Compute SVD for A and B
UA, sigma_A, VA = np.linalg.svd(A, full_matrices=False)
UB, sigma_B, VB = np.linalg.svd(B, full_matrices=False)

# Plot singular values with markers
plt.figure(figsize=(10, 6))
plt.plot(
    range(1, 21),
    sigma_A,
    marker="o",
    label="Singular Values of A (Uniform Distribution)",
)
plt.plot(
    range(1, 21),
    sigma_B,
    marker="s",
    label="Singular Values of B (Normal Distribution)",
)
plt.title("Singular Values of Random Matrices A and B")
plt.xlabel("Singular Value Index")
plt.ylabel("Singular Value")
plt.legend()
plt.grid(True)
plt.show()

In [9]:
A = np.matrix([[1, 2, 1, 1], [2, 2, 2, 2], [1, 2, 1, 1]])

np.set_printoptions(precision=3, suppress=True)
U, S, V = np.linalg.svd(A)

In [10]:
U

matrix([[ 0.482,  0.517, -0.707],
        [ 0.732, -0.682, -0.   ],
        [ 0.482,  0.517,  0.707]])

In [11]:
S

array([5.402, 0.907, 0.   ])

In [12]:
V

matrix([[ 0.449,  0.628,  0.449,  0.449],
        [-0.362,  0.778, -0.362, -0.362],
        [ 0.816,  0.   , -0.408, -0.408],
        [ 0.   ,  0.   , -0.707,  0.707]])